apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drawio
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: chart
    repoURL: https://github.com/a-mankinenko/docker-drawio
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: b07cc73
        - name: image.tag
          value: latest
  destination:
    name: in-cluster
    namespace: drawio
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
